export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const NEWPLACE = 'NEWPLACE'
export const REMOVEELEMENT = 'REMOVEELEMENT'
export const ADDINFO = 'ADDINFO'
export const CHANGEPOSITION = 'CHANGEPOSITION'
export const CHANGESORT = 'CHANGESORT'
